import { useEffect, useState } from "react";
import { closeHoldRequest, createHoldRequest, fetchTicketHolds, reviewHoldRequest } from "../../api/holds";
import { useAuth } from "../../context/AuthContext";

function readFile(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] || ""); reader.onerror = reject; reader.readAsDataURL(file); }); }
export default function TicketHoldPanel({ ticket }) {
  const { user } = useAuth(); const role = String(user?.role_code || "").toUpperCase(); const [holds, setHolds] = useState([]); const [reason, setReason] = useState(""); const [proof, setProof] = useState(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const uploadBaseUrl = (import.meta.env.VITE_API_BASE_URL || "/api").replace(/\/api\/?$/, "");
  const canSubmit = ["ORG_ADMIN", "ORG_STAFF"].includes(role) && ["OPEN", "IN_PROGRESS"].includes(ticket.status) && String(user?.organization_id) === String(ticket.assigned_organization_id); const canReview = role === "ORG_ADMIN" && String(user?.organization_id) === String(ticket.requesting_organization_id);
  async function load() { try { setHolds(await fetchTicketHolds(ticket.id)); } catch { setError("Unable to load hold requests."); } }
  useEffect(() => { void load(); }, [ticket.id]);
  async function submit(event) { event.preventDefault(); if (!reason.trim()) return; setSaving(true); setError(""); try { const content_base64 = proof ? await readFile(proof) : null; await createHoldRequest({ ticket_id: ticket.id, reason_text: reason, proof: proof ? { file_name: proof.name, mime_type: proof.type, content_base64 } : null }); setReason(""); setProof(null); await load(); } catch (err) { setError(err.response?.data?.error || "Unable to submit hold request."); } finally { setSaving(false); } }
  async function review(id, status) { const rejection_reason = status === "REJECTED" ? window.prompt("Reason for declining this hold request:") : null; if (status === "REJECTED" && !rejection_reason?.trim()) return; try { await reviewHoldRequest(id, { status, rejection_reason }); await load(); } catch (err) { setError(err.response?.data?.error || "Unable to review hold request."); } }
  async function close(id) { if (!window.confirm("Resume this ticket and restart its SLA timer?")) return; try { await closeHoldRequest(id); await load(); } catch (err) { setError(err.response?.data?.error || "Unable to resume this ticket."); } }
  return <section className="panel stack-md" id="hold-requests"><div><span className="eyebrow">SLA pause request</span><h2>Hold requests</h2><p className="section-copy">A hold pauses the SLA timer only after the client Organization Admin approves it. Add proof if it helps explain the delay.</p></div>{canSubmit && !holds.some((item) => item.status === "PENDING") ? <form className="stack-md" onSubmit={submit}><label className="field"><span>Reason for the delay</span><textarea required value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explain why this work needs to pause and when it can continue." /></label><label className="field"><span>Proof image or document (optional)</span><input type="file" accept=".pdf,.png,.jpg,.jpeg,.doc,.docx" onChange={(event) => setProof(event.target.files?.[0] || null)} />{proof ? <small className="muted-text">Selected: {proof.name}</small> : null}</label><button className="button" disabled={saving}>{saving ? "Submitting..." : "Request SLA hold"}</button></form> : null}{error ? <div className="form-error">{error}</div> : null}{holds.length ? <div className="hold-list">{holds.map((hold) => <article className="hold-item" key={hold.id}><div><span className={`status-pill status-${String(hold.status).toLowerCase()}`}>{String(hold.status).toLowerCase()}</span><strong>{hold.submitted_by_name}</strong><p>{hold.reason_text}</p>{hold.attachment_path ? <a className="table-link" href={`${uploadBaseUrl}${hold.attachment_path}`} target="_blank" rel="noreferrer">View attached proof: {hold.attachment_name || "file"}</a> : null}</div>{canReview && hold.status === "PENDING" ? <div className="action-row"><button type="button" className="button button-small" onClick={() => review(hold.id, "APPROVED")}>Approve hold</button><button type="button" className="button button-secondary button-small" onClick={() => review(hold.id, "REJECTED")}>Decline</button></div> : null}{canReview && hold.status === "APPROVED" ? <div className="action-row"><button type="button" className="button button-small" onClick={() => close(hold.id)}>Resume work</button></div> : null}</article>)}</div> : <p className="muted-text">No hold requests have been made for this ticket.</p>}</section>;
}
