import { useEffect, useState } from "react";
import PageHeader from "../../components/layout/PageHeader";
import { fetchMlAdministration, retrainMlModel } from "../../api/ml";

export default function MlAdministrationPage() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [starting, setStarting] = useState(false);
  async function load() { try { setData(await fetchMlAdministration()); setError(""); } catch (err) { setError(err.response?.data?.error || "Unable to load ML administration."); } }
  useEffect(() => { void load(); const timer = window.setInterval(load, 10000); return () => window.clearInterval(timer); }, []);
  async function retrain() { setStarting(true); try { await retrainMlModel(); await load(); } catch (err) { setError(err.response?.data?.error || "Unable to start training."); } finally { setStarting(false); } }
  const training = data?.training; const metrics = data?.metrics;
  return <section className="stack-lg"><PageHeader eyebrow="Machine learning" title="ML administration" description="Monitor the breach-risk model, its training data, and its real ticket predictions." actions={<button className="button" onClick={retrain} disabled={starting || training?.status === "RUNNING"}>{training?.status === "RUNNING" ? "Training in progress..." : "Retrain model"}</button>} />{error ? <div className="panel form-error">{error}</div> : null}{data ? <><div className="report-metrics"><article className="panel"><span>Training data</span><strong>{data.dataset_rows ?? 0}</strong><small>Hybrid training records</small></article><article className="panel"><span>ROC-AUC</span><strong>{metrics?.roc_auc ? `${Math.round(metrics.roc_auc * 100)}%` : "-"}</strong><small>Current model discrimination</small></article><article className="panel"><span>Model status</span><strong>{training?.status?.toLowerCase() || "ready"}</strong><small>{training?.finished_at ? new Date(training.finished_at).toLocaleString() : "No current run"}</small></article><article className="panel"><span>Features</span><strong>{metrics?.features?.length ?? 0}</strong><small>Inputs used for scoring</small></article></div><div className="report-grid"><section className="panel stack-md"><div><span className="eyebrow">Model versions</span><h2>Training history</h2></div>{data.versions.length ? data.versions.map((version) => <div className="report-row" key={`${version.version}-${version.trained_at}`}><div><strong>{version.version}{version.is_active ? " · active" : ""}</strong><span>{version.training_rows} records · {new Date(version.trained_at).toLocaleString()}</span></div><b>{version.roc_auc ? `${Math.round(Number(version.roc_auc) * 100)}%` : "-"}</b></div>) : <p className="muted-text">The model will appear here after its first registered training run.</p>}</section><section className="panel stack-md"><div><span className="eyebrow">Prediction monitoring</span><h2>Ticket outcomes</h2></div>{data.predictions.length ? data.predictions.map((prediction) => <div className="report-row" key={prediction.model_version || "unversioned"}><div><strong>{prediction.model_version || "Pending version"}</strong><span>{prediction.predictions} predictions · {prediction.outcomes} confirmed outcomes</span></div><b>{Math.round(Number(prediction.average_predicted_risk || 0) * 100)}% risk</b></div>) : <p className="muted-text">Ticket predictions will appear as tickets are created and completed.</p>}</section></div></> : <div className="panel">Loading ML administration...</div>}</section>;
}
