import { useEffect, useState } from "react";
import PageHeader from "../../components/layout/PageHeader";
import { downloadOperationsReport, fetchOperationsReport } from "../../api/reports";

export default function OperationsReportPage() {
  const [report, setReport] = useState(null); const [error, setError] = useState("");
  async function load() { try { setReport(await fetchOperationsReport()); setError(""); } catch (err) { setError(err.response?.data?.error || "Unable to load reports."); } }
  useEffect(() => { void load(); }, []);
  async function download() { const blob = await downloadOperationsReport(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "contractorlink-operations-report.csv"; link.click(); URL.revokeObjectURL(url); }
  const metrics = report?.summary || {};
  return <section className="stack-lg"><PageHeader eyebrow="Platform intelligence" title="Operations reports" description="Review service delivery, SLA health, resolution speed, and contractor feedback." actions={<button className="button" onClick={download} disabled={!report}>Download CSV</button>} />{error ? <div className="panel form-error">{error}</div> : null}{report ? <><div className="report-metrics"><article className="panel"><span>Active tickets</span><strong>{metrics.active_tickets}</strong><small>{metrics.total_tickets} total requests</small></article><article className="panel"><span>SLA breaches</span><strong>{metrics.breached_tickets}</strong><small>{metrics.monitored_tickets} tickets monitored</small></article><article className="panel"><span>Resolution time</span><strong>{metrics.avg_resolution_hours ?? "-"}h</strong><small>Average completed work</small></article><article className="panel"><span>Completed tickets</span><strong>{metrics.completed_tickets}</strong><small>Service records closed</small></article></div><div className="report-grid"><section className="panel stack-md"><div><span className="eyebrow">Contractor quality</span><h2>Ratings overview</h2></div>{report.contractors.length ? report.contractors.map((contractor) => <div className="report-row" key={contractor.id}><div><strong>{contractor.name}</strong><span>{contractor.review_count} review(s)</span></div><b>{contractor.average_rating}/5</b></div>) : <p className="muted-text">No contractor reviews have been submitted yet.</p>}</section><section className="panel stack-md"><div><span className="eyebrow">Recent activity</span><h2>Latest tickets</h2></div>{report.recent_tickets.map((ticket) => <div className="report-row" key={ticket.ticket_number}><div><strong>{ticket.ticket_number} · {ticket.title}</strong><span>{ticket.client_name} to {ticket.contractor_name}</span></div><b>{String(ticket.sla_status || ticket.status).toLowerCase()}</b></div>)}</section></div></> : <div className="panel">Loading operations report...</div>}</section>;
}
