import { useEffect, useState } from "react";
import { downloadAuditLogs, fetchAuditLogs } from "../../api/auditLogs";
import { changePassword } from "../../api/auth";
import { fetchNotificationSettings, updateNotificationSettings } from "../../api/notifications";
import PageHeader from "../../components/layout/PageHeader";
import { useAuth } from "../../context/AuthContext";

const defaults = { email_ticket_assigned: true, email_ticket_updated: true, email_sla_breached: true, email_hold_reviewed: true, email_ticket_completed: true };
const alerts = [["email_ticket_assigned", "New ticket assignments", "Email when work is assigned to you or your organization."], ["email_ticket_updated", "Ticket updates", "Email when an active ticket receives an important update."], ["email_sla_breached", "SLA breach alerts", "Email when a ticket reaches its SLA breach point."], ["email_hold_reviewed", "Hold request decisions", "Email when a ticket hold request is approved or rejected."], ["email_ticket_completed", "Ticket completion", "Email when work is marked as completed."]];

function Icon({ type }) { const paths = { password: "M7 11V8a5 5 0 0 1 10 0v3m-11 0h12v9H6v-9Zm6 4v2", notification: "M18 9a6 6 0 1 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9Zm-8 12h4", audit: "M7 3h8l4 4v14H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Zm8 0v5h5M9 13h6M9 17h6" }; return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[type]} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>; }

export default function SettingsPage() {
  const { user, logout } = useAuth();
  const isSuperAdmin = String(user?.role_code || "").toUpperCase() === "SUPER_ADMIN";
  const [open, setOpen] = useState("");
  const [password, setPassword] = useState({ current_password: "", new_password: "", confirm_password: "" });
  const [passwordState, setPasswordState] = useState({ isSubmitting: false, error: "", success: "" });
  const [settings, setSettings] = useState(defaults);
  const [alertState, setAlertState] = useState({ loading: true, saving: false, error: "", success: "" });
  const [audit, setAudit] = useState({ loading: false, downloading: false, error: "", logs: [] });

  useEffect(() => { let alive = true; fetchNotificationSettings().then((data) => alive && setSettings({ ...defaults, ...data })).catch((error) => alive && setAlertState((state) => ({ ...state, error: error.response?.data?.error || "Unable to load notification settings." }))).finally(() => alive && setAlertState((state) => ({ ...state, loading: false }))); return () => { alive = false; }; }, []);
  async function loadAudit() { setAudit((state) => ({ ...state, loading: true, error: "" })); try { const logs = await fetchAuditLogs(); setAudit((state) => ({ ...state, loading: false, logs })); } catch (error) { setAudit((state) => ({ ...state, loading: false, error: error.response?.data?.error || "Unable to retrieve audit logs." })); } }
  function toggle(panel) { setOpen((current) => current === panel ? "" : panel); if (panel === "audit" && !audit.logs.length && !audit.loading) void loadAudit(); }
  async function savePassword(event) { event.preventDefault(); if (password.new_password !== password.confirm_password) { setPasswordState({ isSubmitting: false, error: "New password and confirmation do not match.", success: "" }); return; } setPasswordState({ isSubmitting: true, error: "", success: "" }); try { const result = await changePassword(password); setPasswordState({ isSubmitting: false, error: "", success: result.message || "Password updated successfully. Signing you out..." }); setPassword({ current_password: "", new_password: "", confirm_password: "" }); setTimeout(() => logout(), 1200); } catch (error) { setPasswordState({ isSubmitting: false, error: error.response?.data?.error || "Unable to update password.", success: "" }); } }
  async function saveAlerts(event) { event.preventDefault(); setAlertState((state) => ({ ...state, saving: true, error: "", success: "" })); try { const saved = await updateNotificationSettings(settings); setSettings({ ...defaults, ...saved }); setAlertState((state) => ({ ...state, saving: false, success: "Email notification settings saved." })); } catch (error) { setAlertState((state) => ({ ...state, saving: false, error: error.response?.data?.error || "Unable to save notification settings." })); } }
  async function download() { setAudit((state) => ({ ...state, downloading: true, error: "" })); try { await downloadAuditLogs(); setAudit((state) => ({ ...state, downloading: false })); } catch (error) { setAudit((state) => ({ ...state, downloading: false, error: error.response?.data?.error || "Unable to download audit logs." })); } }
  const card = (key, icon, eyebrow, title, copy, action) => <article className={open === key ? "settings-action-card selected" : "settings-action-card"}><div className="settings-action-icon"><Icon type={icon} /></div><span className="eyebrow">{eyebrow}</span><h3>{title}</h3><p>{copy}</p><button type="button" className="button button-secondary" onClick={() => toggle(key)}>{open === key ? `Close ${action}` : action}</button></article>;
  return <section className="stack-lg settings-page"><PageHeader eyebrow="Workspace controls" title="Settings" description="Manage account security, notification preferences, and platform oversight tools." /><section className="settings-identity panel"><div className="settings-avatar">{String(user?.full_name || "U")[0].toUpperCase()}</div><div><span className="eyebrow">Signed in as</span><h2>{user?.full_name || "User"}</h2><p>{user?.email} · {user?.role_name || "User"}</p></div><div className="settings-identity-org"><span>Workspace</span><strong>{user?.organization || "Platform Internal"}</strong></div></section><section className="settings-action-grid">{card("password", "password", "Account security", "Change password", "Update your password using your current password.", "Change password")}{card("alerts", "notification", "Email alerts", "Notification settings", "Choose which ticket and SLA updates reach your inbox.", "Manage notifications")}{isSuperAdmin ? card("audit", "audit", "Platform oversight", "Audit logs", "Review and download the platform audit trail.", "Get audit logs") : null}</section>
    {open === "password" ? <section className="panel settings-detail-panel"><span className="eyebrow">Password management</span><h3>Choose a new password</h3><p className="section-copy">You will be signed out after the password is updated.</p><form onSubmit={savePassword} className="settings-form stack-md">{[["current_password", "Current password"], ["new_password", "New password"], ["confirm_password", "Confirm new password"]].map(([key, label]) => <label className="field" key={key}><span>{label}</span><input type="password" value={password[key]} minLength={key === "current_password" ? undefined : 8} onChange={(event) => setPassword((current) => ({ ...current, [key]: event.target.value }))} required /></label>)}{passwordState.error ? <div className="form-error">{passwordState.error}</div> : null}{passwordState.success ? <div className="form-success">{passwordState.success}</div> : null}<button className="button button-primary" disabled={passwordState.isSubmitting}>{passwordState.isSubmitting ? "Saving..." : "Save new password"}</button></form></section> : null}
    {open === "alerts" ? <section className="panel settings-detail-panel"><span className="eyebrow">Email preferences</span><h3>Choose your email alerts</h3><p className="section-copy">In-site notifications remain available in the bell menu. These controls only affect email alerts.</p><form onSubmit={saveAlerts} className="stack-md">{alertState.loading ? <p className="muted-text">Loading notification settings...</p> : <div className="notification-preference-list">{alerts.map(([key, label, copy]) => <label className="notification-preference" key={key}><span><strong>{label}</strong><small>{copy}</small></span><input type="checkbox" checked={Boolean(settings[key])} onChange={(event) => setSettings((current) => ({ ...current, [key]: event.target.checked }))} /></label>)}</div>}{alertState.error ? <div className="form-error">{alertState.error}</div> : null}{alertState.success ? <div className="form-success">{alertState.success}</div> : null}<button className="button button-primary" disabled={alertState.loading || alertState.saving}>{alertState.saving ? "Saving..." : "Save notification settings"}</button></form></section> : null}
    {open === "audit" && isSuperAdmin ? <section className="panel settings-detail-panel"><div className="detail-header"><div><span className="eyebrow">Platform audit trail</span><h3>Recent audit logs</h3><p className="section-copy">Important activity recorded across the platform.</p></div><div className="action-row"><button type="button" className="button button-secondary button-small" onClick={() => void loadAudit()} disabled={audit.loading}>{audit.loading ? "Refreshing..." : "Refresh"}</button><button type="button" className="button button-primary button-small" onClick={() => void download()} disabled={audit.downloading}>{audit.downloading ? "Preparing..." : "Download CSV"}</button></div></div>{audit.error ? <div className="form-error">{audit.error}</div> : null}{audit.loading ? <p className="muted-text">Loading the latest audit records...</p> : null}{!audit.loading && audit.logs.length ? <div className="audit-log-list">{audit.logs.map((log) => <article className="audit-log-item" key={log.id}><div><strong>{String(log.action_type || "Activity").replaceAll("_", " ")}</strong><p>{log.actor_name || "System"}{log.actor_email ? ` · ${log.actor_email}` : ""}</p></div><div><span>{log.entity_type || "platform"}</span><time>{log.created_at ? new Date(log.created_at).toLocaleString() : "Unknown time"}</time></div></article>)}</div> : null}{!audit.loading && !audit.logs.length && !audit.error ? <p className="muted-text">No audit logs have been recorded yet.</p> : null}</section> : null}</section>;
}
