import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";
import { fetchTicket, fetchTicketChat, sendTicketChatMessage } from "../../api/tickets";
import { getRealtimeSocket } from "../../realtime/socket";
import PageHeader from "../../components/layout/PageHeader";

export default function TicketChatPage() {
  const { ticketId } = useParams(); const { user, token } = useAuth(); const [ticket, setTicket] = useState(null); const [chat, setChat] = useState(null); const [message, setMessage] = useState(""); const [sending, setSending] = useState(false); const [error, setError] = useState("");
  async function loadChat() { try { setChat(await fetchTicketChat(ticketId)); } catch (err) { setError(err.response?.data?.error || "Unable to load ticket chat."); } }
  useEffect(() => { fetchTicket(ticketId).then(setTicket).catch((err) => setError(err.response?.data?.error || "Unable to load ticket.")); void loadChat(); }, [ticketId]);
  useEffect(() => { const socket = getRealtimeSocket(token); if (!socket) return undefined; const receive = ({ ticket_id, message: incoming }) => { if (String(ticket_id) === String(ticketId)) setChat((current) => current ? { ...current, messages: current.messages.some((item) => item.id === incoming.id) ? current.messages : [...current.messages, incoming] } : current); }; socket.on("ticket-chat:message", receive); return () => socket.off("ticket-chat:message", receive); }, [ticketId, token]);
  async function send(event) { event.preventDefault(); if (!message.trim() || sending) return; setSending(true); try { const sent = await sendTicketChatMessage(ticketId, message.trim()); setChat((current) => ({ ...current, messages: current.messages.some((item) => item.id === sent.id) ? current.messages : [...current.messages, sent] })); setMessage(""); } catch (err) { setError(err.response?.data?.error || "Unable to send message."); } finally { setSending(false); } }
  if (error && !ticket) return <div className="panel form-error">{error}</div>; if (!ticket || !chat) return <div className="panel">Loading ticket chat...</div>;
  const open = chat.thread.status === "OPEN";
  return <section className="stack-lg"><PageHeader eyebrow={ticket.ticket_number} title="Ticket chat" description={`${ticket.title} · ${ticket.requesting_organization_name} to ${ticket.assigned_organization_name}`} actions={<Link className="button button-secondary" to={`/tickets/${ticket.id}`}>Back to ticket</Link>} /><section className="panel ticket-chat-page"><header><div><span className="eyebrow">Live conversation</span><h2>{ticket.title}</h2></div><span className={`status-pill status-${open ? "open" : "locked"}`}>{open ? "Chat open" : "Chat locked"}</span></header><div className="ticket-chat-messages">{chat.messages.length ? chat.messages.map((item) => <article className={`ticket-chat-message ${String(item.sender_user_id) === String(user?.id) ? "mine" : ""}`} key={item.id}><div><strong>{item.sender_name}</strong><span>{item.sender_organization_name || "ContractorLink"}</span></div><p>{item.message_text}</p><time>{new Date(item.created_at).toLocaleString()}</time></article>) : <p className="muted-text">No messages yet. Start the conversation here.</p>}</div><form className="ticket-chat-composer" onSubmit={send}><textarea value={message} onChange={(event) => setMessage(event.target.value)} disabled={!open || sending} placeholder={open ? "Write a work-related message..." : "This chat has ended."} /><button className="button" disabled={!open || !message.trim() || sending}>{sending ? "Sending..." : "Send"}</button></form></section></section>;
}
